// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeOvobJ2yvhhrY85515FF8i8cMc48CAQE',
    appId: '1:611624175290:web:318a32d45da1e203722483',
    messagingSenderId: '611624175290',
    projectId: 'chat-app-fb7b2',
    authDomain: 'chat-app-fb7b2.firebaseapp.com',
    storageBucket: 'chat-app-fb7b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAH8rtcHfQO2_DxdI1gFdJoPGcAuQqSwo',
    appId: '1:611624175290:android:2ef6c44c93fba967722483',
    messagingSenderId: '611624175290',
    projectId: 'chat-app-fb7b2',
    storageBucket: 'chat-app-fb7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGqKDGJW8ykk2EY5kjgSxo_kSO4Erh5k',
    appId: '1:611624175290:ios:7ee8e57f183cc11e722483',
    messagingSenderId: '611624175290',
    projectId: 'chat-app-fb7b2',
    storageBucket: 'chat-app-fb7b2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGqKDGJW8ykk2EY5kjgSxo_kSO4Erh5k',
    appId: '1:611624175290:ios:7ee8e57f183cc11e722483',
    messagingSenderId: '611624175290',
    projectId: 'chat-app-fb7b2',
    storageBucket: 'chat-app-fb7b2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeOvobJ2yvhhrY85515FF8i8cMc48CAQE',
    appId: '1:611624175290:web:92408897a4bd6d5e722483',
    messagingSenderId: '611624175290',
    projectId: 'chat-app-fb7b2',
    authDomain: 'chat-app-fb7b2.firebaseapp.com',
    storageBucket: 'chat-app-fb7b2.appspot.com',
  );
}
